# -*- coding: utf-8 -*-
"""employee_assignment-resubmit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jK5JlxldB-Pas-rdf0G1DnptHu31qWTw
"""

employee= {101: {'name': 'Suhas', 'age': 21, 'department': 'ISE', 'salary': 5000}
           ,102: {'name': 'Sahitya', 'age': 25, 'department': 'BTE', 'salary': 10000}
           ,103: {'name': 'Sanjana', 'age': 30, 'department': 'ECE', 'salary': 15000}}

def add_employee():
  emp_id = int(input("enter employee id:"))
  if emp_id in employee:
    print("employee already exists")
    return
  else:
    name = input("enter employee name:")
    age = int(input("enter employee age:"))
    department = input("enter employee department:")
    salary = int(input("enter employee salary:"))
    employee[emp_id] = {'name': name, 'age': age, 'department': department, 'salary': salary}
    print("employee added successfully")

def view_employee():
  if not employee:
    print("no employees found")
  else:
    print(f"{'ID':<5} {'Name':<20} {'Age':<5} {'Department':<15} {'Salary':<10}")
    print("-" * 60)
    for emp_id, details in employee.items():
      print(f"{emp_id:<5} {details['name']:<20} {details['age']:<5} {details['department']:<15} {details['salary']:<10}")

def search_employee():
  emp_id = int(input("enter employee id:"))
  if emp_id not in employee:
    print(\n"employee not found")
    return
  else:
    emp_info = employee[emp_id]
    print(\nf"Employee ID: {emp_id}")
    print(f"Name: {emp_info['name']}")
    print(f"Age: {emp_info['age']}")
    print(f"Department: {emp_info['department']}")
    print(f"Salary: {emp_info['salary']}")

#name: Employee's name.
#age: Employee's age.
#department: Employee's department.
#salary: Employee's monthly salary.
def mainmenu():
  while True:
    print("\n--- Employee Management System Menu ---")
    print("To Add Employee - 1\nView All Employees-2\nSearch for Employee-3\nExit-4")
    choice = int(input("enter your choice(1-4)"))
    if choice==1:
      print('---------add employee---------')
      add_employee()
    elif choice==2:
      print('---------view all employees---------')
      view_employee()
    elif choice==3:
      print('---------search for employee---------')
      search_employee()
    elif choice==4:
      print('---------thank you , exiting---------')
      break
    else:
      print('---------invalid choice---------')
if __name__ == "__main__":
  mainmenu()

